org.gradle.jvmargs=-Xmx3072m -Xss16m -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx2048m -Xss16m
kotlin.compiler.execution.strategy=daemon
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.mpp.androidSourceSetLayoutVersion=2
android.suppressUnsupportedCompileSdk=36
org.gradle.parallel=true
org.gradle.caching=true
